// Reiseziele-Datenbank mit hochwertigen Bildern
const destinations = [
    // Europa
    {
        id: 1,
        name: "Paris, Frankreich",
        region: "Europa",
        description: "Die Stadt der Liebe mit dem Eiffelturm, erstklassigen Museen und charmanten Cafés.",
        bestSeason: ["spring", "autumn"],
        type: ["city"],
        budget: ["moderate", "luxury"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?auto=format&fit=crop&w=800",
        highlights: ["Eiffelturm", "Louvre", "Notre-Dame", "Montmartre"],
        features: ["Romantik", "Kunst", "Kulinarik", "Mode"]
    },
    {
        id: 2,
        name: "Rom, Italien",
        region: "Europa",
        description: "Die ewige Stadt mit antiken Ruinen, Renaissance-Kunst und köstlicher italienischer Küche.",
        bestSeason: ["spring", "autumn"],
        type: ["city"],
        budget: ["moderate", "luxury"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?auto=format&fit=crop&w=800",
        highlights: ["Kolosseum", "Vatikan", "Trevi-Brunnen", "Forum Romanum"],
        features: ["Geschichte", "Kunst", "Kulinarik", "Architektur"]
    },
    {
        id: 3,
        name: "Santorini, Griechenland",
        region: "Europa",
        description: "Weiße Häuser mit blauen Kuppeln auf einer Vulkaninsel mit spektakulären Sonnenuntergängen.",
        bestSeason: ["spring", "summer", "autumn"],
        type: ["beach", "city"],
        budget: ["luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=800",
        highlights: ["Oia", "Caldera", "Vulkanstrände", "Weingüter"],
        features: ["Romantik", "Ausblicke", "Fotografie", "Kulinarik"]
    },
    {
        id: 4,
        name: "Barcelona, Spanien",
        region: "Europa",
        description: "Lebendige Küstenstadt mit einzigartiger Architektur, Stränden und lebhaftem Nachtleben.",
        bestSeason: ["spring", "summer", "autumn"],
        type: ["city", "beach"],
        budget: ["moderate", "luxury"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=800",
        highlights: ["Sagrada Familia", "Park Güell", "Las Ramblas", "Barceloneta"],
        features: ["Architektur", "Strand", "Tapas", "Kunst"]
    },
    {
        id: 5,
        name: "London, Vereinigtes Königreich",
        region: "Europa",
        description: "Weltstadt mit historischen Wahrzeichen, Museen und dynamischer Kulturszene.",
        bestSeason: ["spring", "summer"],
        type: ["city"],
        budget: ["moderate", "luxury"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800",
        highlights: ["Big Ben", "Tower of London", "British Museum", "Buckingham Palace"],
        features: ["Geschichte", "Kultur", "Shopping", "Parks"]
    },
    {
        id: 6,
        name: "Amalfiküste, Italien",
        region: "Europa",
        description: "Dramatische Küstenlandschaft mit pittoresken Dörfern und azurblauem Meer.",
        bestSeason: ["spring", "summer", "autumn"],
        type: ["beach", "nature"],
        budget: ["luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1612360267266-60e2962b5c02?auto=format&fit=crop&w=800",
        highlights: ["Positano", "Ravello", "Capri", "Küstenstraße"],
        features: ["Landschaft", "Kulinarik", "Romantik", "Fotografie"]
    },
    {
        id: 7,
        name: "Alpen, Schweiz",
        region: "Europa",
        description: "Majestätische Berglandschaft mit schneebedeckten Gipfeln und idyllischen Dörfern.",
        bestSeason: ["summer", "winter"],
        type: ["mountains", "nature"],
        budget: ["moderate", "luxury"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1531210483974-4f8c1f33fd35?auto=format&fit=crop&w=800",
        highlights: ["Matterhorn", "Interlaken", "Zermatt", "Jungfraujoch"],
        features: ["Skifahren", "Wandern", "Berglandschaft", "Naturschönheit"]
    },
    {
        id: 8,
        name: "Amsterdam, Niederlande",
        region: "Europa",
        description: "Kanaldurchzogene Stadt mit historischen Gebäuden und zahlreichen Kunstmuseen.",
        bestSeason: ["spring", "autumn"],
        type: ["city"],
        budget: ["moderate"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1576924542622-772281b13aa8?auto=format&fit=crop&w=800",
        highlights: ["Anne-Frank-Haus", "Rijksmuseum", "Grachten", "Vondelpark"],
        features: ["Kultur", "Kunst", "Fahrradfahren", "Architektur"]
    },
    {
        id: 9,
        name: "Prag, Tschechien",
        region: "Europa",
        description: "Märchenhafte Stadt mit gotischer Architektur und reicher Geschichte.",
        bestSeason: ["spring", "autumn"],
        type: ["city"],
        budget: ["budget", "moderate"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=800",
        highlights: ["Prager Burg", "Karlsbrücke", "Altstadt", "Astronomische Uhr"],
        features: ["Geschichte", "Architektur", "Bier", "Kultur"]
    },
    {
        id: 10,
        name: "Island",
        region: "Europa",
        description: "Land aus Feuer und Eis mit Vulkanen, Geysiren, Wasserfällen und Gletschern.",
        bestSeason: ["summer"],
        type: ["nature"],
        budget: ["moderate", "luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1529963183134-61a90db47eaf?auto=format&fit=crop&w=800",
        highlights: ["Blaue Lagune", "Nordlichter", "Goldener Kreis", "Schwarze Strände"],
        features: ["Naturwunder", "Geothermie", "Wandern", "Fotografie"]
    },
    {
        id: 11,
        name: "Toskana, Italien",
        region: "Europa",
        description: "Hügelige Landschaft mit Weinbergen, mittelalterlichen Dörfern und Renaissance-Kunst.",
        bestSeason: ["spring", "autumn"],
        type: ["nature", "city"],
        budget: ["moderate", "luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1568822617270-2c1579f8dfe2?auto=format&fit=crop&w=800",
        highlights: ["Florenz", "Siena", "Weintouren", "Zypressen-Landschaften"],
        features: ["Wein", "Kunst", "Kulinarik", "Landschaft"]
    },
    {
        id: 12,
        name: "Kroatische Küste",
        region: "Europa",
        description: "Kristallklares Wasser, historische Städte und über tausend Inseln entlang der Adriaküste.",
        bestSeason: ["summer"],
        type: ["beach", "city"],
        budget: ["budget", "moderate"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1567346587603-00d66cde4daa?auto=format&fit=crop&w=800",
        highlights: ["Dubrovnik", "Split", "Plitvice-Seen", "Hvar"],
        features: ["Strände", "Geschichte", "Inselhüpfen", "Natur"]
    },
    {
        id: 13,
        name: "Norwegische Fjorde",
        region: "Europa",
        description: "Dramatische Fjordlandschaften mit steilen Felswänden und spektakulären Wasserfällen.",
        bestSeason: ["summer"],
        type: ["nature", "mountains"],
        budget: ["moderate", "luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1601439678777-b2b3c56fa627?auto=format&fit=crop&w=800",
        highlights: ["Geirangerfjord", "Bergen", "Trolltunga", "Preikestolen"],
        features: ["Naturschönheit", "Wandern", "Bootsfahrten", "Fotografie"]
    },
    {
        id: 14,
        name: "Berlin, Deutschland",
        region: "Europa",
        description: "Dynamische Kulturmetropole mit faszinierender Geschichte und lebendiger Kunstszene.",
        bestSeason: ["spring", "summer", "autumn"],
        type: ["city"],
        budget: ["budget", "moderate"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1566404791232-af9fe8c8e4d6?auto=format&fit=crop&w=800",
        highlights: ["Brandenburger Tor", "Reichstag", "Museumsinsel", "East Side Gallery"],
        features: ["Geschichte", "Kunst", "Nachtleben", "Kultur"]
    },
    {
        id: 15,
        name: "Lappland, Finnland",
        region: "Europa",
        description: "Winterwunderland mit Nordlichtern, Hundeschlittenfahrten und dem Dorf des Weihnachtsmanns.",
        bestSeason: ["winter"],
        type: ["nature"],
        budget: ["moderate", "luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1518094279906-7c2540718cb8?auto=format&fit=crop&w=800",
        highlights: ["Nordlichter", "Rentiere", "Iglus", "Weihnachtsmanndorf"],
        features: ["Winter", "Abenteuer", "Naturphänomen", "Tierwelt"]
    },
    
    // Asien
    {
        id: 16,
        name: "Tokio, Japan",
        region: "Asien",
        description: "Hypermoderne Metropole mit Tradition, exzellenter Küche und einzigartiger Popkultur.",
        bestSeason: ["spring", "autumn"],
        type: ["city"],
        budget: ["moderate", "luxury"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?auto=format&fit=crop&w=800",
        highlights: ["Shibuya-Kreuzung", "Tsukiji-Fischmarkt", "Meiji-Schrein", "Shinjuku"],
        features: ["Technologie", "Essen", "Kultur", "Shopping"]
    },
    {
        id: 17,
        name: "Kyoto, Japan",
        region: "Asien",
        description: "Kulturelles Herz Japans mit hunderten Tempeln, traditionellen Gärten und Geisha-Kultur.",
        bestSeason: ["spring", "autumn"],
        type: ["city"],
        budget: ["moderate", "luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?auto=format&fit=crop&w=800",
        highlights: ["Fushimi Inari", "Arashiyama", "Kinkaku-ji", "Gion"],
        features: ["Kultur", "Tempel", "Tradition", "Zen-Gärten"]
    },
    {
        id: 18,
        name: "Bali, Indonesien",
        region: "Asien",
        description: "Tropisches Paradies mit Reisterrassen, spirituellen Tempeln und surferfreundlichen Stränden.",
        bestSeason: ["spring", "summer", "autumn"],
        type: ["beach", "nature", "city"],
        budget: ["budget", "moderate", "luxury"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1573790387438-4da905039392?auto=format&fit=crop&w=800",
        highlights: ["Ubud", "Tanah Lot", "Reisterrassen", "Uluwatu"],
        features: ["Spiritualität", "Strand", "Kultur", "Natur"]
    },
    {
        id: 19,
        name: "Bangkok, Thailand",
        region: "Asien",
        description: "Pulsierender urbaner Dschungel mit opulenten Tempeln, Märkten und weltberühmtem Streetfood.",
        bestSeason: ["winter", "spring"],
        type: ["city"],
        budget: ["budget", "moderate"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1563492065599-3520f775eeed?auto=format&fit=crop&w=800",
        highlights: ["Großer Palast", "Wat Arun", "Chatuchak-Markt", "Khao San Road"],
        features: ["Tempel", "Essen", "Shopping", "Nachtleben"]
    },
    {
        id: 20,
        name: "Vietnamesisches Hochland",
        region: "Asien",
        description: "Bergige Region mit terrassierten Reisfeldern, ethnischen Minderheiten und kühlem Klima.",
        bestSeason: ["winter", "spring"],
        type: ["nature", "mountains"],
        budget: ["budget", "moderate"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1518638150340-f706e86654de?auto=format&fit=crop&w=800",
        highlights: ["Sapa", "Reisterrassen", "Bergdörfer", "Trekkingtouren"],
        features: ["Landschaft", "Kultur", "Wandern", "Fotografie"]
    },
    {
        id: 21,
        name: "Angkor, Kambodscha",
        region: "Asien",
        description: "Weitläufiges Tempelareal mit eindrucksvollen Steinmonumenten des Khmer-Reiches.",
        bestSeason: ["winter"],
        type: ["city", "nature"],
        budget: ["budget", "moderate"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1524099116203-86a184d10a2c?auto=format&fit=crop&w=800",
        highlights: ["Angkor Wat", "Bayon", "Ta Prohm", "Banteay Srei"],
        features: ["Geschichte", "Architektur", "Kultur", "Natur"]
    },
    {
        id: 22,
        name: "Malediven",
        region: "Asien",
        description: "Traumhafte Atolle mit türkisfarbenem Wasser, schneeweißen Stränden und Overwater-Bungalows.",
        bestSeason: ["winter", "spring"],
        type: ["beach"],
        budget: ["luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=800",
        highlights: ["Schnorcheln", "Overwater-Villen", "Korallenriffe", "Wassersport"],
        features: ["Luxus", "Romantik", "Unterwasserwelt", "Entspannung"]
    },
    {
        id: 23,
        name: "Varanasi, Indien",
        region: "Asien",
        description: "Eine der ältesten kontinuierlich bewohnten Städte der Welt mit spiritueller Bedeutung am Ganges.",
        bestSeason: ["winter"],
        type: ["city"],
        budget: ["budget"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1627894483216-2138af692e32?auto=format&fit=crop&w=800",
        highlights: ["Ghats", "Ganges", "Abendzeremonie", "Altstadt"],
        features: ["Spiritualität", "Kultur", "Geschichte", "Fotografie"]
    },
    {
        id: 24,
        name: "Peking, China",
        region: "Asien",
        description: "Chinas Hauptstadt mit beeindruckenden Kaiserpalästen, Hutongs und der Nähe zur Großen Mauer.",
        bestSeason: ["spring", "autumn"],
        type: ["city"],
        budget: ["moderate"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1599571234909-29ed5d1321d6?auto=format&fit=crop&w=800",
        highlights: ["Verbotene Stadt", "Große Mauer", "Sommerpalast", "Himmelstempel"],
        features: ["Geschichte", "Architektur", "Kultur", "Essen"]
    },
    {
        id: 25,
        name: "Dubai, VAE",
        region: "Asien",
        description: "Futuristische Metropole in der Wüste mit Wolkenkratzern, Luxus-Shopping und Wüstenabenteuern.",
        bestSeason: ["winter", "autumn"],
        type: ["city", "beach"],
        budget: ["luxury"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=800",
        highlights: ["Burj Khalifa", "Palm Jumeirah", "Dubai Mall", "Wüstensafari"],
        features: ["Luxus", "Architektur", "Shopping", "Abenteuer"]
    },
    
    // Afrika
    {
        id: 26,
        name: "Serengeti, Tansania",
        region: "Afrika",
        description: "Ikonische Savanne mit einer der größten Tierwanderungen der Welt und den Big Five.",
        bestSeason: ["winter", "summer"],
        type: ["nature"],
        budget: ["moderate", "luxury"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1547970810-dc1eac37d174?auto=format&fit=crop&w=800",
        highlights: ["Big Five", "Große Migration", "Ngorongoro-Krater", "Massai-Dörfer"],
        features: ["Safari", "Tierwelt", "Landschaft", "Abenteuer"]
    },
    {
        id: 27,
        name: "Kapstadt, Südafrika",
        region: "Afrika",
        description: "Kosmopolitische Stadt am Fuße des Tafelbergs mit Stränden, Weinland und kultureller Vielfalt.",
        bestSeason: ["spring", "autumn", "summer"],
        type: ["city", "beach", "nature"],
        budget: ["moderate"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=800",
        highlights: ["Tafelberg", "Kap der Guten Hoffnung", "Weinland", "V&A Waterfront"],
        features: ["Natur", "Wein", "Kultur", "Strände"]
    },
    {
        id: 28,
        name: "Marrakesch, Marokko",
        region: "Afrika",
        description: "Farbenfrohe Stadt mit labyrinthartigen Märkten, Palästen und berberkulturellem Erbe.",
        bestSeason: ["spring", "autumn"],
        type: ["city"],
        budget: ["budget", "moderate"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1597212618440-806262de4f6b?auto=format&fit=crop&w=800",
        highlights: ["Djemaa el-Fna", "Souks", "Jardin Majorelle", "Bahia-Palast"],
        features: ["Kultur", "Architektur", "Shopping", "Essen"]
    },
    {
        id: 29,
        name: "Ägyptische Pyramiden",
        region: "Afrika",
        description: "Antike Wunderwerke und Nekropolen der Pharaonen mit dem legendären Sphinx.",
        bestSeason: ["winter", "autumn"],
        type: ["city", "nature"],
        budget: ["moderate"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1572252009286-268acec5ca0a?auto=format&fit=crop&w=800",
        highlights: ["Pyramiden von Gizeh", "Sphinx", "Kairo", "Nilkreuzfahrt"],
        features: ["Geschichte", "Archäologie", "Kultur", "Antike"]
    },
    {
        id: 30,
        name: "Sansibar, Tansania",
        region: "Afrika",
        description: "Tropische Insel mit weißen Sandstränden, historischer Altstadt und Gewürzplantagen.",
        bestSeason: ["winter", "summer"],
        type: ["beach", "city"],
        budget: ["moderate"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1589553416260-f586c8f1514f?auto=format&fit=crop&w=800",
        highlights: ["Stone Town", "Strände", "Gewürztouren", "Delfin-Watching"],
        features: ["Strand", "Kultur", "Geschichte", "Wassersport"]
    },
    
    // Nordamerika
    {
        id: 31,
        name: "New York City, USA",
        region: "Nordamerika",
        description: "Die Stadt, die niemals schläft, mit ikonischer Skyline, Weltklasse-Museen und Broadway-Shows.",
        bestSeason: ["spring", "autumn"],
        type: ["city"],
        budget: ["moderate", "luxury"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=800",
        highlights: ["Central Park", "Empire State Building", "Broadway", "MoMA"],
        features: ["Kultur", "Shopping", "Restaurants", "Unterhaltung"]
    },
    {
        id: 32,
        name: "Grand Canyon, USA",
        region: "Nordamerika",
        description: "Geologisches Wunderwerk mit spektakulären Ausblicken und Hiking-Möglichkeiten.",
        bestSeason: ["spring", "autumn"],
        type: ["nature"],
        budget: ["moderate"],
        duration: ["weekend", "week"],
        image: "https://images.unsplash.com/photo-1615551043360-33de8b5f410c?auto=format&fit=crop&w=800",
        highlights: ["South Rim", "North Rim", "Helicopter Tour", "Colorado River"],
        features: ["Natur", "Wandern", "Fotografie", "Abenteuer"]
    },
    {
        id: 33,
        name: "Yellowstone, USA",
        region: "Nordamerika",
        description: "Erster Nationalpark der Welt mit Geysiren, heißen Quellen und reicher Tierwelt.",
        bestSeason: ["summer"],
        type: ["nature"],
        budget: ["moderate"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1576615745100-ac1d1dc82ae6?auto=format&fit=crop&w=800",
        highlights: ["Old Faithful", "Grand Prismatic Spring", "Yellowstone Lake", "Wildlife"],
        features: ["Natur", "Geothermie", "Tierwelt", "Wandern"]
    },
    {
        id: 34,
        name: "Vancouver, Kanada",
        region: "Nordamerika",
        description: "Entspannte Küstenstadt zwischen Bergen und Meer mit hervorragender Lebensqualität.",
        bestSeason: ["summer"],
        type: ["city", "nature"],
        budget: ["moderate"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1559511260-66a654ae982a?auto=format&fit=crop&w=800",
        highlights: ["Stanley Park", "Grouse Mountain", "Granville Island", "Gastown"],
        features: ["Natur", "Outdoor-Aktivitäten", "Kultur", "Essen"]
    },
    {
        id: 35,
        name: "Kuba",
        region: "Nordamerika",
        description: "Karibische Insel mit Kolonialstädten, Vintage-Autos, Tabakplantagen und Traumstränden.",
        bestSeason: ["winter", "spring"],
        type: ["city", "beach"],
        budget: ["budget", "moderate"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800",
        highlights: ["Havanna", "Viñales", "Trinidad", "Varadero"],
        features: ["Musik", "Geschichte", "Strände", "Kultur"]
    },
    {
        id: 36,
        name: "Banff National Park, Kanada",
        region: "Nordamerika",
        description: "Atemberaubender Nationalpark in den kanadischen Rocky Mountains mit türkisfarbenen Seen.",
        bestSeason: ["summer", "autumn"],
        type: ["nature", "mountains"],
        budget: ["moderate", "luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1609790259935-766357d3c616?auto=format&fit=crop&w=800",
        highlights: ["Lake Louise", "Moraine Lake", "Icefields Parkway", "Banff Springs Hotel"],
        features: ["Berglandschaft", "Tierwelt", "Wandern", "Fotografie"]
    },
    
    // Südamerika
    {
        id: 37,
        name: "Machu Picchu, Peru",
        region: "Südamerika",
        description: "Mysteriöse Inkastadt in den Anden mit faszinierender Architektur und atemberaubender Lage.",
        bestSeason: ["winter", "autumn"],
        type: ["mountains", "nature"],
        budget: ["moderate"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1587595431973-160d0d94add1?auto=format&fit=crop&w=800",
        highlights: ["Inkaruinen", "Inka-Trail", "Cusco", "Heiliges Tal"],
        features: ["Geschichte", "Wandern", "Kultur", "Naturwunder"]
    },
    {
        id: 38,
        name: "Rio de Janeiro, Brasilien",
        region: "Südamerika",
        description: "Lebhafte Stadt zwischen Bergen und Meer mit ikonischen Wahrzeichen und Stränden.",
        bestSeason: ["winter", "spring"],
        type: ["city", "beach"],
        budget: ["moderate"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=800",
        highlights: ["Cristo Redentor", "Zuckerhut", "Copacabana", "Ipanema"],
        features: ["Strände", "Aussichtspunkte", "Kultur", "Nachtleben"]
    },
    {
        id: 39,
        name: "Galapagos-Inseln, Ecuador",
        region: "Südamerika",
        description: "Einzigartiges Naturparadies mit endemischer Tierwelt und unberührten Landschaften.",
        bestSeason: ["winter", "spring"],
        type: ["nature", "beach"],
        budget: ["luxury"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1548736614-128923bc6f9d?auto=format&fit=crop&w=800",
        highlights: ["Riesenschildkröten", "Blaufußtölpel", "Lavafelsen", "Schnorcheln"],
        features: ["Tierwelt", "Naturbeobachtung", "Ökotourismus", "Fotografie"]
    },
    {
        id: 40,
        name: "Patagonien, Argentinien/Chile",
        region: "Südamerika",
        description: "Wilde Region am Ende der Welt mit dramatischen Bergen, Gletschern und endlosen Steppen.",
        bestSeason: ["summer"],
        type: ["nature", "mountains"],
        budget: ["moderate", "luxury"],
        duration: ["twoweeks"],
        image: "https://images.unsplash.com/photo-1531761535209-180857e963b9?auto=format&fit=crop&w=800",
        highlights: ["Torres del Paine", "Perito Moreno", "Mount Fitz Roy", "Feuerland"],
        features: ["Wildnis", "Wandern", "Landschaft", "Abenteuer"]
    },
    
    // Ozeanien
    {
        id: 41,
        name: "Great Barrier Reef, Australien",
        region: "Ozeanien",
        description: "Größtes Korallenriff der Welt mit spektakulärer Unterwasserwelt und Tauchmöglichkeiten.",
        bestSeason: ["winter", "spring", "autumn"],
        type: ["beach", "nature"],
        budget: ["moderate", "luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800",
        highlights: ["Korallenriffe", "Schnorcheln", "Tauchen", "Whitsunday Islands"],
        features: ["Meeresleben", "Naturwunder", "Wassersport", "Fotografie"]
    },
    {
        id: 42,
        name: "Sydney, Australien",
        region: "Ozeanien",
        description: "Ikonische Hafenstadt mit weltberühmter Oper, schönen Stränden und urbanem Lebensstil.",
        bestSeason: ["spring", "autumn", "summer"],
        type: ["city", "beach"],
        budget: ["moderate", "luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=800",
        highlights: ["Opernhaus", "Harbour Bridge", "Bondi Beach", "The Rocks"],
        features: ["Architektur", "Strände", "Kultur", "Stadtleben"]
    },
    {
        id: 43,
        name: "Neuseeland, Südinsel",
        region: "Ozeanien",
        description: "Landschaftlich atemberaubende Insel mit Fjorden, Gletschern, Bergen und Abenteuermöglichkeiten.",
        bestSeason: ["spring", "autumn", "summer"],
        type: ["nature", "mountains"],
        budget: ["moderate", "luxury"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=800",
        highlights: ["Milford Sound", "Queenstown", "Franz Josef Gletscher", "Abel Tasman"],
        features: ["Landschaft", "Outdoor-Aktivitäten", "Abenteuer", "Natur"]
    },
    {
        id: 44,
        name: "Fidschi",
        region: "Ozeanien",
        description: "Tropisches Südseeparadies mit weißen Stränden, freundlichen Einheimischen und Korallenriffen.",
        bestSeason: ["spring", "autumn", "winter"],
        type: ["beach"],
        budget: ["moderate", "luxury"],
        duration: ["week", "twoweeks"],
        image: "https://images.unsplash.com/photo-1559128010-7c1ad6e1b6a5?auto=format&fit=crop&w=800",
        highlights: ["Yasawa Inseln", "Schnorcheln", "Traditionelle Dörfer", "Wasserfälle"],
        features: ["Entspannung", "Wassersport", "Kultur", "Inselhopping"]
    },
    {
        id: 45,
        name: "Bora Bora, Französisch-Polynesien",
        region: "Ozeanien",
        description: "Ikonische Insel mit türkisfarbenem Wasser, Overwater-Bungalows und vulkanischem Zentrum.",
        bestSeason: ["winter", "spring"],
        type: ["beach"],
        budget: ["luxury"],
        duration: ["week"],
        image: "https://images.unsplash.com/photo-1589197331516-4d84b72bb818?auto=format&fit=crop&w=800",
        highlights: ["Mount Otemanu", "Matira Beach", "Lagune", "Overwater-Bungalows"],
        features: ["Luxus", "Romantik", "Wassersport", "Entspannung"]
    }
];